### ISSUE TITLE
SVGs not standard ?

### ISSUE THREAD

**Issue by taherv** [egonelbre/gophers#13]
I cant seem to open these svg files in standard image editing software, tried a few well known names.
Photoshop says this is not valid PostScript.

Is there some software you recommend I use ? Better, if free :)

Great artwork. BTW. Please accept my compliments on sharing these.

**Comment by taherv** [comment]
FWIW I tried opening standing.svg. Not sure if the others work.

**Comment by egonelbre** [comment]
I use Inkscape to convert them from svg to the thumbnails, so all `svg`-s should be viewable using it. I've switched to Affinity Designer for newer images, however, they usually have svg export that (hopefully) works in Inkscape.

As far as I know, Photoshop does not directly support SVG, you would need Illustrator for it.

**Comment by taherv** [comment]
I am so sorry for the inconvenience caused. I was unable to open it even in Illustrator, then realized that the download of the svg file from your gitub repo was not working due to a network issue on my side.

Once I was able to download the complete file, I was able to edit it in illustrator.

Closing this issue, apologies again for raising a false alarm.
