### ISSUE TITLE
Emoji set

### ISSUE THREAD

**Issue by egonelbre** [egonelbre/gophers#2]
Create a set of small gophers with different expressions.

**Comment by Ataeraxia** [comment]
![go-gopher-emoji-0](https://user-images.githubusercontent.com/11510098/31569377-8be09c38-b048-11e7-800b-58417618daf3.png)
Is this a good start? I can make more if wanted.

**Comment by egonelbre** [comment]
That's cute >^.^<.

The repo issues are more of a things I may want to do someday... but, if you make a emoji set of your own that would be awesome, because it seems there are other people who like the idea, and I have no clue when I intend to do it. The more the merrier.

As, for the style, I cannot stress this enough, develop your own style, and the following is what I like or think would be nicer.

As for my style, I would have probably went either the Android emoji look or https://github.com/egonelbre/gophers/blob/master/icon/icons.svg. And I feel that ears are quite essential part of the gopher.

A quick sketch, roughly what I would do, (it still can be significantly improved): 
![mockup](https://user-images.githubusercontent.com/192964/31576302-a390cb7e-b100-11e7-92fd-8c7b510900ac.png)
