### ISSUE TITLE
request: gopherhug

### ISSUE THREAD

**Issue by ghost** [egonelbre/gophers#8]
Requesting :gopherhug: slack emoji
I'm imagining a side view of pink gopher and blue gopher smushed together with little arm stubs not even reaching the back

**Comment by egonelbre** [comment]
![hug](https://user-images.githubusercontent.com/192964/54479510-1c2a4480-4826-11e9-99d2-b7168f1219de.png)

**Comment by egonelbre** [comment]
![hug](https://user-images.githubusercontent.com/192964/54479559-9a86e680-4826-11e9-85d1-41b112bff7aa.png)

**Comment by egonelbre** [comment]
![hug](https://user-images.githubusercontent.com/192964/54479604-049f8b80-4827-11e9-9996-96f655c64798.png)

**Comment by ghost** [comment]
wonderful! you're the best

![](https://user-images.githubusercontent.com/192964/54479604-049f8b80-4827-11e9-9996-96f655c64798.png)
